{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "agent-platform.name" . }}-{{ .Values.environment }}-sa
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "agent-platform.labels" . | nindent 4 }}
    security-tier: {{ .Values.serviceAccount.securityTier | default "restricted" }}
    environment: {{ .Values.global.environment }}
    region: {{ index .Values.global.multiRegion.regions 0 }}
  annotations:
    # Lifecycle hooks for proper resource management
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: "before-hook-creation"
    
    # Security annotations
    security.platform.agent/token-rotation: {{ .Values.serviceAccount.tokenRotation | default "enabled" | quote }}
    security.platform.agent/last-rotation: {{ now | date "2006-01-02T15:04:05Z07:00" | quote }}
    security.platform.agent/security-tier: {{ .Values.serviceAccount.securityTier | default "restricted" | quote }}
    
    # Auth0 integration annotations
    auth0.platform.agent/enabled: {{ .Values.global.security.auth.provider | eq "auth0" | quote }}
    auth0.platform.agent/jwt-validation: {{ .Values.global.security.auth.jwtValidation | quote }}
    
    # Monitoring annotations
    monitoring.platform.agent/enabled: "true"
    {{- include "agent-platform.monitoringAnnotations" . | nindent 4 }}
    
    # Service mesh integration
    service-mesh.platform.agent/injection: {{ .Values.serviceAccount.meshEnabled | default "enabled" | quote }}
    istio.io/service-account: {{ template "agent-platform.name" . }}-{{ .Values.environment }}-sa
    
    # IAM and Vault integration
    iam.platform.agent/role: {{ .Values.serviceAccount.iamRole | default (printf "%s-%s-role" (include "agent-platform.name" .) .Values.environment) | quote }}
    vault.platform.agent/policy: {{ .Values.serviceAccount.vaultPolicy | default (printf "%s-%s-policy" (include "agent-platform.name" .) .Values.environment) | quote }}
    
    # Multi-region support
    {{- if .Values.global.multiRegion.enabled }}
    multiregion.platform.agent/enabled: "true"
    multiregion.platform.agent/primary-region: {{ index .Values.global.multiRegion.regions 0 | quote }}
    multiregion.platform.agent/failover-enabled: {{ .Values.global.multiRegion.failover.enabled | quote }}
    multiregion.platform.agent/failover-method: {{ .Values.global.multiRegion.failover.method | quote }}
    {{- end }}

automountServiceAccountToken: {{ .Values.serviceAccount.automountToken | default false }}

{{- if .Values.global.image.pullSecrets }}
imagePullSecrets:
{{- range .Values.global.image.pullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}

{{- end }}