apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: agent-platform
  labels:
    app: api-gateway
    component: config
    environment: production
data:
  KONG_ADMIN_URL: "http://localhost:8001"
  KONG_PROXY_URL: "http://localhost:8000"
  KONG_RATE_LIMIT_PER_MINUTE: "100"
  CORS_ALLOWED_ORIGINS: "https://agent-platform.com"
  LOG_LEVEL: "info"
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  REQUEST_TIMEOUT: "30000"
  MAX_PAYLOAD_SIZE: "10mb"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-generator-config
  namespace: agent-platform
  labels:
    app: agent-generator
    component: config
    environment: production
data:
  NODE_ENV: "production"
  PORT: "3000"
  API_VERSION: "v1"
  LOG_LEVEL: "info"
  METRICS_RETENTION_DAYS: "90"
  PROMETHEUS_ENDPOINT: "http://prometheus-server:9090"
  MAX_AGENT_MEMORY: "2Gi"
  MAX_AGENT_CPU: "1000m"
  AGENT_TIMEOUT: "300000"
  MAX_CONCURRENT_AGENTS: "50"
  HEALTH_CHECK_INTERVAL: "30000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: integration-service-config
  namespace: agent-platform
  labels:
    app: integration-service
    component: config
    environment: production
data:
  ZOHO_BASE_URL: "https://www.zohoapis.com/crm/v3"
  ZOHO_TIMEOUT: "30000"
  ZOHO_RETRY_ATTEMPTS: "3"
  ZOHO_RETRY_DELAY: "1000"
  RMS_BASE_URL: "https://api.rms.com/v1"
  RMS_TIMEOUT: "30000"
  RMS_RETRY_ATTEMPTS: "3"
  RMS_RETRY_DELAY: "1000"
  INTEGRATION_CACHE_TTL: "3600"
  MAX_CONCURRENT_REQUESTS: "100"
  CIRCUIT_BREAKER_THRESHOLD: "0.5"
  HEALTH_CHECK_INTERVAL: "60000"