apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: agent-platform
  labels:
    app: agent-platform
    component: database
    managed-by: platform
    rotation-enabled: "true"
  annotations:
    secret-rotation.agent-platform.io/enabled: "true"
    secret-rotation.agent-platform.io/schedule: "168h"  # 7 days rotation
    encryption.agent-platform.io/kms-key: "arn:aws:kms:region:account:key/key-id"
    audit.agent-platform.io/enabled: "true"
    audit.agent-platform.io/retention: "90d"
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # base64 encoded "postgres"
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=  # base64 encoded "postgres_password"
  POSTGRES_DB: YWdlbnRfcGxhdGZvcm0=  # base64 encoded "agent_platform"
  POSTGRES_HOST: bG9jYWxob3N0  # base64 encoded "localhost"
  POSTGRES_PORT: NTQzMg==  # base64 encoded "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-credentials
  namespace: agent-platform
  labels:
    app: agent-platform
    component: auth
    managed-by: platform
    rotation-enabled: "true"
  annotations:
    secret-rotation.agent-platform.io/enabled: "true"
    secret-rotation.agent-platform.io/schedule: "720h"  # 30 days rotation
    encryption.agent-platform.io/kms-key: "arn:aws:kms:region:account:key/key-id"
    audit.agent-platform.io/enabled: "true"
    audit.agent-platform.io/retention: "90d"
type: Opaque
data:
  AUTH0_DOMAIN: eW91ci10ZW5hbnQuYXV0aDAuY29t  # base64 encoded "your-tenant.auth0.com"
  AUTH0_CLIENT_ID: eW91cl9jbGllbnRfaWQ=  # base64 encoded "your_client_id"
  AUTH0_CLIENT_SECRET: eW91cl9jbGllbnRfc2VjcmV0  # base64 encoded "your_client_secret"
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2tleQ==  # base64 encoded "your_jwt_secret_key"
---
apiVersion: v1
kind: Secret
metadata:
  name: integration-credentials
  namespace: agent-platform
  labels:
    app: agent-platform
    component: integration
    managed-by: platform
    rotation-enabled: "true"
  annotations:
    secret-rotation.agent-platform.io/enabled: "true"
    secret-rotation.agent-platform.io/schedule: "720h"  # 30 days rotation
    encryption.agent-platform.io/kms-key: "arn:aws:kms:region:account:key/key-id"
    audit.agent-platform.io/enabled: "true"
    audit.agent-platform.io/retention: "90d"
type: Opaque
data:
  ZOHO_CLIENT_ID: eW91cl96b2hvX2NsaWVudF9pZA==  # base64 encoded "your_zoho_client_id"
  ZOHO_CLIENT_SECRET: eW91cl96b2hvX2NsaWVudF9zZWNyZXQ=  # base64 encoded "your_zoho_client_secret"
  RMS_API_KEY: eW91cl9ybXNfYXBpX2tleQ==  # base64 encoded "your_rms_api_key"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: agent-platform
  labels:
    app: agent-platform
    component: aws
    managed-by: platform
    rotation-enabled: "true"
  annotations:
    secret-rotation.agent-platform.io/enabled: "true"
    secret-rotation.agent-platform.io/schedule: "720h"  # 30 days rotation
    encryption.agent-platform.io/kms-key: "arn:aws:kms:region:account:key/key-id"
    audit.agent-platform.io/enabled: "true"
    audit.agent-platform.io/retention: "90d"
type: Opaque
data:
  AWS_ACCESS_KEY_ID: eW91cl9hd3NfYWNjZXNzX2tleQ==  # base64 encoded "your_aws_access_key"
  AWS_SECRET_ACCESS_KEY: eW91cl9hd3Nfc2VjcmV0X2tleQ==  # base64 encoded "your_aws_secret_key"
  AWS_REGION: dXMtd2VzdC0y  # base64 encoded "us-west-2"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: agent-platform
  labels:
    app: agent-platform
    component: redis
    managed-by: platform
    rotation-enabled: "true"
  annotations:
    secret-rotation.agent-platform.io/enabled: "true"
    secret-rotation.agent-platform.io/schedule: "720h"  # 30 days rotation
    encryption.agent-platform.io/kms-key: "arn:aws:kms:region:account:key/key-id"
    audit.agent-platform.io/enabled: "true"
    audit.agent-platform.io/retention: "90d"
type: Opaque
data:
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ=  # base64 encoded "redis_password"
  REDIS_HOST: bG9jYWxob3N0  # base64 encoded "localhost"
  REDIS_PORT: NjM3OQ==  # base64 encoded "6379"