# Prometheus Configuration v2.45.0
# Primary configuration file for AGENT AI Platform monitoring system

global:
  # Global settings for all scrape targets
  scrape_interval: 15s     # Default scrape interval
  evaluation_interval: 15s  # Evaluation interval for rules
  scrape_timeout: 10s      # Global scrape timeout
  external_labels:
    environment: production
    region: primary
    platform: agent_ai
    cluster: main

# Load alert rules from external file
rule_files:
  - "alert-rules.yml"

# Scrape configurations for monitoring targets
scrape_configs:
  # Prometheus self-monitoring
  - job_name: prometheus
    honor_labels: true
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: monitoring
          component: prometheus

  # API Gateway monitoring
  - job_name: api_gateway
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          service: gateway
          component: api
    relabel_configs:
      - source_labels: ['__address__']
        target_label: instance
        replacement: 'api_gateway_${1}'

  # Agent Generator service monitoring
  - job_name: agent_generator
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets: ['agent-generator:3000']
        labels:
          service: generator
          component: agent

  # NLP Engine monitoring
  - job_name: nlp_engine
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets: ['nlp-engine:5000']
        labels:
          service: engine
          component: nlp

  # Integration Service monitoring
  - job_name: integration_service
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets: ['integration-service:4000']
        labels:
          service: integration
          component: service

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'
          - 'alertmanager-backup:9093'
      timeout: 5s
      scheme: https
      tls_config:
        cert_file: /etc/prometheus/certs/prometheus.crt
        key_file: /etc/prometheus/certs/prometheus.key
        ca_file: /etc/prometheus/certs/ca.crt

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention:
      time: 15d
    out_of_order_time_window: 30m

# Security configuration
tls_server_config:
  cert_file: /etc/prometheus/certs/prometheus.crt
  key_file: /etc/prometheus/certs/prometheus.key
  min_version: TLS12

# Web configuration
web:
  console:
    templates: /etc/prometheus/consoles
    libraries: /etc/prometheus/console_libraries